<div id="container">
	<h1>Bem-vindo ao Mpudi!</h1>

	<div id="body">
		<p>Esta página foi gerada dinamicamente pelo MpuDi.</p>

		<p>Se desejar alterar esta página saiba que podes encontrá-la em:</p>
		<code>app/views/index.phtml</code>

		<p>O controller correspondente desta página encontra-se em:</p>
		<code>app/controllers/BasicoController.php</code>

		<p>Se é a primeira vez que usa o MpuDi, recomendamos que leia antes a documentação <a href="user_guide/">Guia do Utilizador</a>.</p>
	</div>

	<p class="footer">Desenvolvido por Lukau Garcia * Mpudi versão 1.0</p>
</div>